plugins {
    id 'java'
    id 'me.champeau.jmh' version '0.7.2'
}

group = 'renu.gusain'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    jmhImplementation libs.jmh.core
    jmhAnnotationProcessor libs.jmh.generator

}
jmh {
    warmupIterations = 3
    iterations = 5
    fork = 1
    benchmarkMode = ['AverageTime']
    timeUnit = 'ms'
}

test {
    useJUnitPlatform()
}